config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :documentary_films
  resources :series
  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
    validates :title, :duration, :description, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :title, :duration, :description, presence: true
end

app/models/series.rb
class Series < ApplicationRecord
    validates :title, :duration, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController
  
    before_action :set_documentary_film, only: [:edit, :update, :destroy]
  
    def index
      @documentary_films = DocumentaryFilm.all
    end
  
    def new
      @documentary_film = DocumentaryFilm.new
  
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @documentary_film }
      end
    end
  
    def create
      @documentary_film = DocumentaryFilm.new(documentary_film_params)
  
      if @documentary_film.save
        redirect_to documentary_films_path, notice: 'Documental creado exitosamente.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @documentary_film.update(documentary_film_params)
        redirect_to documentary_films_path, notice: 'Documental actualizado exitosamente.'
      else
        render :edit
      end
    end
  
    def destroy
      @documentary_film.destroy
      redirect_to documentary_films_path, notice: 'Documental eliminado exitosamente.'
    end
  
    private
  
    def set_documentary_film
      @documentary_film = DocumentaryFilm.find(params[:id])
    end
  
    def documentary_film_params
      params.require(:documentary_film).permit(:title, :duration, :description)
    end
end
  

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :set_movie, only: [:edit, :update, :destroy]
  
    def index
      @movies = Movie.all
   
    end

    def new
        @movie = Movie.new
      
        respond_to do |format|
          format.html { render :new }
          format.json { render json: @movie }
        end
      end

    def create
      @movie = Movie.new(movie_params)
  
      if @movie.save
        redirect_to movies_path, notice: 'Película creada exitosamente.'
      else
        render :new
      end
    end
  
    def edit
      
    end
  
    def update
      if @movie.update(movie_params)
        redirect_to movies_path, notice: 'Película actualizada exitosamente.'
      else
        render :edit
      end
    end
  
    def destroy
      @movie.destroy
      redirect_to movies_path, notice: 'Película eliminada exitosamente.'
    end
  
    private
  
    def set_movie
      @movie = Movie.find(params[:id])
    end
  
    def movie_params
      params.require(:movie).permit(:title, :duration, :description)
    end
end
  

app/controllers/series_controller.rb
class SeriesController < ApplicationController

    before_action :set_serie, only: [:edit, :update, :destroy]
  
    def index
      @series = Serie.all
   
    end

    def new
        @series = Serie.new
      
        respond_to do |format|
          format.html { render :new }
          format.json { render json: @serie }
        end
      end

    def create
      @serie = Serie.new(serie_params)
  
      if @serie.save
        redirect_to movies_path, notice: 'Serie creada exitosamente.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @serie.update(serie_params)
        redirect_to series_path, notice: 'Serie actualizada exitosamente.'
      else
        render :edit
      end
    end
  
    def destroy
      @serie.destroy
      redirect_to series_path, notice: 'Serie eliminada exitosamente.'
    end
  
    private
  
    def set_serie
      @serie = Serie.find(params[:id])
    end
  
    def serie_params
      params.require(:serie).permit(:title, :duration, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentary_films/edit.html.erb
<div class="container">
<h1 class="mt-5 mb-4">Editar Documental</h1>
  <%= form_with(model: @documentary, url: documentary_path(@documentary), method: :patch, class: 'mt-5') do |form| %>
    <div class="mb-3">
      <%= form.label :title, 'Título', class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :duration, 'Duración', class: 'form-label' %>
      <%= form.text_area :duration, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :description, 'Descripción', class: 'form-label' %>
      <%= form.text_field :description, class: 'form-control' %>
    </div>

  <div class="mb-3">
      <%= form.submit 'Guardar', class: 'btn btn-primary' %>
      <%= link_to 'Volver', documentary_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>

</div>

app/views/documentary_films/index.html.erb
<div class="container">
<h1 class="mt-4 mb-3">Bienvenido al buscador de películas</h1>

<h2 class="mt-4 mb-3" >Películas</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Título</th>
      <th>Duración</th>
      <th>Descripción</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @documentary_films.each do |document| %>
      <tr>
        <td><%= document.title %></td>
        <td><%= document.duration %></td>
        <td><%= document.description %></td>
        <td><%= link_to 'Editar', edit_documentary_films_path(documentary_films), class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Eliminar', documentary_films, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-primary btn-sm'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar Nuevo Documental',  new_documentary_film_path, class: 'btn btn-primary btn-sm'%>

</div>

app/views/documentary_films/new.html.erb
<div class="container">
  <h1 class="mt-5 mb-4">Agregar Documental</h1>

  <%= form_with(model: @documentary, url: documentary_path, class: 'needs-validation', novalidate: true) do |form| %>
    <div class="form-group mb-4">
      <%= form.label :title, 'Titulo' %>
      <%= form.text_field :title, class: 'form-control', required: true %>
      <div class="invalid-feedback">
        Titulo es requerido.
      </div>
    </div>

    <div class="form-group mb-4">
      <%= form.label :duration, 'Duración' %>
      <%= form.text_area :duration, class: 'form-control', rows: 5, required: true %>
      <div class="invalid-feedback">
        Duration es requerida.
      </div>
    </div>

    <div class="form-group mb-4">
      <%= form.label :description, 'Descripción' %>
      <%= form.text_field :description, class: 'form-control', required: true %>
      <div class="invalid-feedback">
      Descripción es requerido.
      </div>
    </div>

    <div class="form-group mb-4">
      <%= form.submit 'Guardar', class: 'btn btn-primary' %>
      <%= link_to 'Volver', documentary_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/documentary_films/show.html.erb
<div class="container">
  <h1 class="mt-5 mb-4">Detalles del Documental</h1>

  <p><strong>Titulo:</strong> <%= @documentary.title %></p>
  <p><strong>Duración:</strong> <%= @documentary.duration %></p>
  <p><strong>Descripción:</strong> <%= @documentary.description %></p>

  <div class="form-group mb-4">
    <%= link_to 'Editar', edit_documentary_path(@documentary), class: 'btn btn-primary' %>
    <%= link_to 'Volver', documentary_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeliculasApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<div class="container">
<h1 class="mt-5 mb-4">Editar película</h1>
  <%= form_with(model: @movie, url: movie_path(@movie), method: :patch, class: 'mt-5') do |form| %>
    <div class="mb-3">
      <%= form.label :title, 'Titulo', class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :duration, 'Duración', class: 'form-label' %>
      <%= form.text_area :duration, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :description, 'Description', class: 'form-label' %>
      <%= form.text_field :description, class: 'form-control' %>
    </div>

  <div class="mb-3">
      <%= form.submit 'Guardar', class: 'btn btn-primary' %>
      <%= link_to 'Volver', movies_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>

</div>

app/views/movies/index.html.erb
<div class="container">
<h1 class="mt-5 mb-4">Bienvenido al buscador de películas</h1>

<h2 class="mt-5 mb-4">Películas</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Título</th>
      <th>Duración</th>
      <th>Descripción</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.duration %></td>
        <td><%= movie.description %></td>
        <td><%= link_to 'Editar', edit_movie_path(movie), class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Eliminar', movie, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-primary btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar nueva película', new_movie_path, class: 'btn btn-primary btn-sm' %>
</div>

app/views/movies/new.html.erb
<div class="container">
<h1 class="mt-5 mb-4">Agregar nueva película</h1>

<%= form_with(model: @movie, url: movies_path, local: true) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Volver', movies_path, class: 'btn btn-primary'  %>
</div>

app/views/movies/show.html.erb
<div class="container">
  <h1 class="mt-5 mb-4">Detalles de la película</h1>

  <p><strong>Titulo:</strong> <%= @movie.title %></p>
  <p><strong>Duración:</strong> <%= @movie.duration %></p>
  <p><strong>Descripción:</strong> <%= @movie.description %></p>

  <div class="form-group mb-4">
    <%= link_to 'Editar', edit_movie_path(@movie), class: 'btn btn-primary' %>
    <%= link_to 'Volver', movies_path, class: 'btn btn-primary'  %>
  </div>
</div>

app/views/series/edit.html.erb
<div class="container">
<h1 class="mt-5 mb-4">Editar serie</h1>
  <%= form_with(model: @serie, url: series_path(@serie), method: :patch, class: 'mt-5') do |form| %>
    <div class="mb-3">
      <%= form.label :title, 'Titulo', class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :duration, 'Duración', class: 'form-label' %>
      <%= form.text_area :duration, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :description, 'Descripción', class: 'form-label' %>
      <%= form.text_field :description, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.submit 'Guardar', class: 'btn btn-primary' %>
      <%= link_to 'Volver', series_index_path, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/series/index.html.erb
<div class="container">
  <h1 class="mt-5 mb-4">Series</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Titulo</th>
        <th>Duración</th>
        <th>Descripción</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @series.each do |serie| %>
        <tr>
         <td><%= serie.title %></td>
         <td><%= serie.duration %></td>
        <td><%= serie.description %></td>
        <td><%= link_to 'Mostrar', series_path(serie), class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Editar', edit_series_path(serie),class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Eliminar', series_path(serie), method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar esta película?' }, class: 'btn btn-danger btn-sm' %>
</td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Agregar Serie', new_series_path, class: 'btn btn-success' %>
  <%= link_to 'Volver', root_path, class: 'btn btn-secondary' %>
  
</div>

app/views/series/new.html.erb
<div class="container">
  <h1 class="mt-5 mb-4">Agregar Serie</h1>

  <%= form_with(model: @serie, url: series_index_path, class: 'needs-validation', novalidate: true) do |form| %>
    <div class="form-group mb-4">
      <%= form.label :title, 'Titulo' %>
      <%= form.text_field :title, class: 'form-control', required: true %>
      <div class="invalid-feedback">
        Nombre es requerido.
      </div>
    </div>

    <div class="form-group mb-4">
      <%= form.label :duration, 'Duración' %>
      <%= form.text_area :duration, class: 'form-control', rows: 5, required: true %>
      <div class="invalid-feedback">
        Sinopsis es requerida.
      </div>
    </div>

    <div class="form-group mb-4">
      <%= form.label :description, 'Description' %>
      <%= form.text_field :description, class: 'form-control', required: true %>
      <div class="invalid-feedback">
        Director es requerido.
      </div>
    </div>

    <div class="form-group mb-4">
      <%= form.submit 'Guardar', class: 'btn btn-primary' %>
      <%= link_to 'Volver', series_index_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/series/show.html.erb
<div class="container">
  <h1 class="mt-5 mb-4">Detalles de la serie</h1>

  <p><strong>Titulo:</strong> <%= @serie.title %></p>
  <p><strong>Duración:</strong> <%= @serie.duration %></p>
  <p><strong>Descripción:</strong> <%= @serie.description %></p>

  <div class="form-group mb-4">
    <%= link_to 'Editar', edit_series_path(@serie), class: 'btn btn-primary' %>
    <%= link_to 'Volver', series_index_path, class: 'btn btn-primary' %>
  </div>
</div>